# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: めもらんだむ
email: chirimenspiral@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  これは単なる個人的なおぼえがきです。あってるかもしれないしまちがっているかもしれない。ほかのだれかの役にたつことがあったとしてもきっとそれは偶然です。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chirimenmonster.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "chirimenmonster/chirimenmonster.github.io"
twitter_username: chirimenspiral
github_username:  chirimenmonster
lang: ja
timezone: Asia/Tokyo

# Build settings
markdown: kramdown
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


google_analytics: UA-59819729-5

# jekyll-seo-tag
locale: ja_JP
tagline: 個人的なおぼえがき
author:
  twitter: chirimenspiral
twitter:
  username: chirimenspiral
  card: summary
social:
  name: Chirimen
  links:
    - https://twitter.com/chirimenspiral
    - https://github.com/chirimenmonster


# jekyll-paginate
paginate: 5
paginate_path: "/./page:num"


# Site Settings for bulma-clean-theme
defaults:
  -
    scope:
      path: "404.html"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chirimen"
      show_sidebar: true
